name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 
publish_to: 'none'

version: 2.2.0+5

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.0.0
  synchronized: ^3.0.0
  path: ^1.8.0
  # sqfentity_gen: '>=2.2.0+5 <3.0.0'
  sqfentity_gen:
    git:
      url: https://github.com/quicktel-solution/sqfEntity.git
      ref: branch-x
      path: sqfentity_gen
  sqflite_common: ^2.0.1+1
  sqflite_common_ffi: ^2.0.0+3
  meta: ^1.7.0
  

# dependency_overrides:
#  sqfentity_gen:
#    path: ../sqfentity_gen